### ISSUE TITLE
Build instructions and requirements needed?

### ISSUE THREAD

**Issue by Rong-Yao** [tesseract2048/d2gs#8]
I've wanted to test that version of d2gs and I've used MSVS 2008 Express but build fails with
1>fatal error RC1110: could not open .\res\d2server.rc
1>Project : error PRJ0002 : Error result 1 returned from 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\rc.exe'.

And maybe I'm doing something wrong. Not sure now.

**Comment by tesseract2048** [comment]
Issue fixed.
